/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Character {
  'passiveSkills' : Array<string>,
  'name' : string,
  'role' : GameRole,
  'activeSkillName' : string,
  'activeSkillDescription' : string,
}
export type GameRole = { 'support' : null } |
  { 'rusher' : null } |
  { 'sniper' : null };
export type LaunchStatus = { 'live' : null } |
  { 'comingSoon' : null } |
  { 'preRegister' : null };
export interface _SERVICE {
  'addCharacter' : ActorMethod<
    [string, GameRole, string, string, Array<string>],
    undefined
  >,
  'getAllCharacters' : ActorMethod<[], Array<Character>>,
  'getCharacter' : ActorMethod<[string], Character>,
  'getLaunchStatus' : ActorMethod<[], LaunchStatus>,
  'getTotalPlayers' : ActorMethod<[], bigint>,
  'getTotalRegistrations' : ActorMethod<[], bigint>,
  'preRegister' : ActorMethod<[string, string], undefined>,
  'updateLaunchStatus' : ActorMethod<[LaunchStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];