/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GameRole = IDL.Variant({
  'support' : IDL.Null,
  'rusher' : IDL.Null,
  'sniper' : IDL.Null,
});
export const Character = IDL.Record({
  'passiveSkills' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'role' : GameRole,
  'activeSkillName' : IDL.Text,
  'activeSkillDescription' : IDL.Text,
});
export const LaunchStatus = IDL.Variant({
  'live' : IDL.Null,
  'comingSoon' : IDL.Null,
  'preRegister' : IDL.Null,
});

export const idlService = IDL.Service({
  'addCharacter' : IDL.Func(
      [IDL.Text, GameRole, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'getCharacter' : IDL.Func([IDL.Text], [Character], ['query']),
  'getLaunchStatus' : IDL.Func([], [LaunchStatus], ['query']),
  'getTotalPlayers' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalRegistrations' : IDL.Func([], [IDL.Nat], ['query']),
  'preRegister' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateLaunchStatus' : IDL.Func([LaunchStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GameRole = IDL.Variant({
    'support' : IDL.Null,
    'rusher' : IDL.Null,
    'sniper' : IDL.Null,
  });
  const Character = IDL.Record({
    'passiveSkills' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'role' : GameRole,
    'activeSkillName' : IDL.Text,
    'activeSkillDescription' : IDL.Text,
  });
  const LaunchStatus = IDL.Variant({
    'live' : IDL.Null,
    'comingSoon' : IDL.Null,
    'preRegister' : IDL.Null,
  });
  
  return IDL.Service({
    'addCharacter' : IDL.Func(
        [IDL.Text, GameRole, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'getCharacter' : IDL.Func([IDL.Text], [Character], ['query']),
    'getLaunchStatus' : IDL.Func([], [LaunchStatus], ['query']),
    'getTotalPlayers' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalRegistrations' : IDL.Func([], [IDL.Nat], ['query']),
    'preRegister' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateLaunchStatus' : IDL.Func([LaunchStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };